### ISSUE TITLE
ticketmaster-launchpad

### ISSUE THREAD

**Issue by zedtux** [hybridgroup/taskmapper#13]
Hello all,

I've tried to send you an email to the contact address from your website, but I've got an nondelivery message, so I use this to contact you :-)

I'm trying to create the ticketmaster-launchpad provider for launchpad.net, but as I'm not an ActiveResource expert, and as launchpad.net do not follow ActiveResource rules, it's hard for me to make it working.

So is there someone to help me or do implement it please?
(In a first step, I'm trying to implement project and ticket search)

**Comment by kiafaldorius** [comment]
We can help guide you through the process a bit. Thank you for the interest!

Launchpad authentication is a wee-bit difficult since it uses Oauth to authenticate. I don't think there's any ruby launchpad libraries at the moment, but I could be wrong. (If there is one, it would make implementing it a lot easier.)
https://help.launchpad.net/API/SigningRequests

There is another ticketmaster provider that had Oauth2, but I don't remember which one at the moment. In the first step you can just implement a public interface.

Do you know how to access and interface with the API through normal ruby code?

**Comment by zedtux** [comment]
I agree, and also I don't need for my project Oauth authentication. ;-)

When I have tried to create the launchpad.net provider, I've studied it's documentation, and compare how works others ticketmaster providers.
I saw that with ActiveResource, routes should be something like:
- For all projects: http://api.address.tld/prefix/projects.json
- For 1 project: http://api.address.tld/prefix/projects/id_or_name.json
  But launchpad.net work in that way:
- For all projects: http://api.address.tld/prefix/projects.json
- For 1 project: http://api.address.tld/prefix/id_or_name.json

So it's not possible to directly map with ActiveResource to the launchpad.net API.
Also, I mean, no, I don't know how to interface with the API.
(Also, I've discovered what is and how work ActiveResource...)

So now, I presume that we must do something more low level, isn't it?

**Comment by zedtux** [comment]
Help?

**Comment by kiafaldorius** [comment]
Sorry, this got lost in the big slurry of my github notifications. I'm down to 38 unread now...

Yes, you'll have to dig a little more low level. You'll need something to query launchpad and then use ticketmaster to use that to turn the results into ticketmaster objects.

Does that make sense?

**Comment by zedtux** [comment]
Yes it make sense.

I will try again to do the ticketmaster-launchpad...

**Comment by kiafaldorius** [comment]
Thanks, let me know if you need any help. Sorry again for taking so long to reply. I've caught up on the backlog of notifications and should be able to reply faster now.

**Comment by zedtux** [comment]
No problemo ;-)
