### ISSUE TITLE
CLI could use man pages

### ISSUE THREAD

**Issue by deadprogram** [hybridgroup/taskmapper#3]
"man pages are important if you have a command line interface" - @defunkt #RubyMidwest

'nuff said!

**Comment by kiafaldorius** [comment]
Although I would like to have man pages for ticketmaster's CLI interface, rubygems does not facilitate the creation of proper UNIX-style man pages (disregard for a moment the horrendous state of ruby and rubygems on Windows).

There is of course, gem-man by defunkt whom you quoted, however, it does have its design flaws (you can't get a man page for tm; you have to query for ticketmaster). And since the majority of tm's functionality is passed through subcommands, it doesn't make sense for me to have one enormous page. In lieu of gem man and UNIX man pages, we have, since the beginning of the cli, 'tm help' or 'tm [subcommand] --help'.

And as my defense, I ask you to execute 'man gem' from your terminal. It's ever so descriptive man entry reads:

> DESCRIPTION
>      RubyGems is a sophisticated package manager for the Ruby programming language.
> 
> ```
>  For more information about it, you can use its --help flag. There is also online documentation
>  available at "http://docs.rubygems.org".
> ```

**Comment by deadprogram** [comment]
OK, I surrender on this one
